---
- name: Aquire Auth token 
  shell: dcos config show core.dcos_acs_token
  register: auth_token
  changed_when: False


- name: Create Key pair 
  command: "dcos security org service-accounts keypair {{service.name}}.pem {{service.name}}-pub.pem creates={{service.name}}.pem"


- name: Create service account as ID
  command: "dcos security org service-accounts create -p {{service.name}}-pub.pem -d '{{service.name}} service account' {{service.name}}"


- name: Create service secret as Password
  command: "dcos security secrets create-sa-secret {% if edcos_security_mode == 'strict'%} --strict {% endif %} {{service.name}}.pem {{service.name}} {{service.name}}/{{service.secret_name | default('secret') }}"


- name: Create permissions for {{ service.name }}
  uri:
    url: "{{dcos_cluster_url}}/acs/api/v1/acls/{{item.perm}}"
    method: PUT
    validate_certs: False
    headers: 
      Authorization: "token={{auth_token.stdout}}"
    body_format: json
    body: ' { "description": "{{item.desc}}" } '
    status_code: 409, 201 #201 means created
  with_items: "{{service.permissions}}"


- name: Assign the permissions to {{ service.name }}
  uri:
    url: "{{dcos_cluster_url}}/acs/api/v1/acls/{{item.perm}}/users/{{service.name}}/{{item.action}}"
    method: PUT
    validate_certs: False
    headers: 
      Authorization: "token={{auth_token.stdout}}"  
    status_code: 409, 204 # 204 means no content(success)
  with_items: "{{service.permissions}}"