---
- name: Install NFS package 
  yum: name=nfs-utils state=present


# domain names are very impotant for NFSv4 to work - all clients and server must be in the same base doamin
- block:
    - name: Update /etc/hosts for NFS 
      become: yes
      blockinfile:
        path: /etc/hosts
        block: |
            {{ hostvars[item]['ansible_' + dcos_nic_name].ipv4.address }} {{ hostvars[item].ansible_hostname }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
      with_inventory_hostnames: 
        - dcos_slaves:dcos_slaves_public:dcos_bootstrap

    - name: Mapping user names and group IDs to NFSv4 IDs 
      lineinfile: 'dest=/etc/idmapd.conf regexp="^DOMAIN =" line="DOMAIN = {{nfs_base_domain}}" state=present create=yes'        
  when: nfs_version | version_compare('4', operator='eq')


- name: Open NFS related ports 
  firewalld:
    service: "{{item}}"
    permanent: true
    state: enabled
  with_items: 
    - nfs
    - mountd
    - rpc-bind


- name: Start and Enable NFS related services 
  systemd: "name={{item}} state=restarted enabled=yes daemon_reload=yes"
  with_items:
    - rpc-bind
    - nfs-server 


- name: Ensure if shared directory exists
  file: "path={{item.dir}} state=/directory"
  with_items: "{{nfs_exports}}"


- name: Update /etc/exports 
  lineinfile: dest=/etc/exports regexp="^{{item.dir}}" line="{{item.dir}} {{item.hosts}}({{item.options}}) " state=present create=yes
  with_items: "{{nfs_exports}}"


- name: Re-export all entries from /etc/exports
  command: exportfs -ra
