---
- name: Generates config for {{ item.name }}
  template:
    src: "{{item.package}}-config.json.j2"
    dest: "{{dcos_bootstrap_root_path}}/packages/{{item.name}}-config.json"
  with_items: "{{services}}"


- name: Deploy {{ item.name }}
  command: "{{ custom_type == 'True' | ternary('dcos marathon app add {{dcos_bootstrap_root_path}}/packages/{{item.name}}-config.json' , 'dcos package install --options={{dcos_bootstrap_root_path}}/packages/{{item.name}}-config.json {{item.package}} --yes)' }}"
  with_items: "{{services}}"