---
- name: Do pre-tasks for {{pre_tasks}}
  include: pre-tasks-{{pre_tasks}}.yml
  when: pre_tasks is defined 


- name: Generates config for {{ item.name }}
  template:
    src: "{{service.package}}-config.json.j2"
    dest: "{{dcos_bootstrap_root_path}}/packages/{{service.name}}-config.json"


- name: Deploy {{ item.name }}
  command: "dcos package install --options={{dcos_bootstrap_root_path}}/packages/{{service.name}}-config.json {{service.package}} --yes"


- name: Do post-tasks for {{post_tasks}}
  include: pre-tasks-{{post_tasks}}.yml
  when: post_tasks is defined 
