---
- name: Do pre-tasks for {{pre_tasks}}
  include: pre-tasks-{{pre_tasks}}.yml
  when: pre_tasks is defined 


- name: Generates config for {{ service.name }}
  template:
    src: "{{service.package}}-config.json.j2"
    dest: "{{dcos_bootstrap_root_path}}/packages/{{service.name}}-config.json"


- name: Deploy {{ service.name }}
  command: >
    {% if custom_type is defined and custom_type == 'app' %}
        dcos marathon app add {{service.name}}-config.json
     {% elif custom_type is defined and custom_type == 'none' %}
       echo 'do nothing'
     {% else %}
        dcos package install --options={{service.name}}-config.json {{service.package}} --yes
     {% endif %}
  args: 
    chdir: "{{dcos_bootstrap_root_path}}/packages"


- name: Do post-tasks for {{post_tasks}}
  include: post-tasks-{{post_tasks}}.yml
  when: post_tasks is defined 
