
---
- name: Generates marathon config for each role
  template:
    src: "{{item.0.name}}-config.json.j2"
    dest: "{{dcos_bootstrap_root_path}}/packages/{{item.0.name}}-config.json"
  with_subelements:
    - "{{services}}"
    - "role"


- name: Launch  with each role
  command: "dcos package install --options={{dcos_bootstrap_root_path}}/packages/{{item.0.name}}-config.json {{item.0.package_name}} --yes" 
  with_subelements:
    - "{{services}}"
    - "role"
    