---
- name: Docker login 
  become: yes
  docker_login:
    username: "{{docker_hub_id}}"
    password: "{{docker_hub_pwd}}"
    email: "{{docker_hub_mail}}"


- name: Archive docker credential
  become: yes
  command: tar cvzf docker.tar.gz .docker  


- name: Put docker credential to DC/OS root directory for marathon-ee
  become: yes
  copy: remote_src=True src=docker.tar.gz dest="{{ dcos_bootstrap_root_path }}/genconf/serve" owner="{{ansible_user_id}}" group={{ansible_user_id}}


- name: Docker pull Marathon-ee image 
  become: yes
  docker_image: 
    name: "{{marathon_ee_image}}" 
    pull: True


- name: Docker logout
  become: yes
  docker_login:
    state: absent


- name: Restart docker 
  become: yes
  systemd: name=docker state=restarted


- name: Run web container for docker credential
  become: yes
  docker_container: 
    name: boot-nginx
    image: nginx
    state: started
    ports: "{{dcos_bootstrap_port}}:80"
    volumes: "{{ dcos_bootstrap_root_path }}/genconf/serve:/usr/share/nginx/html:ro"
  changed_when: False


- name: Tag and push Marathon-ee to cluster registery
  become: yes
  shell: |
          docker tag {{marathon_ee_image}} {{hostvars[groups['dcos_slaves_public'][0]]['ansible_' + dcos_nic_name]['ipv4']['address']}}:15000/{{service.options.image}}
          docker push {{hostvars[groups['dcos_slaves_public'][0]]['ansible_' + dcos_nic_name]['ipv4']['address']}}:15000/{{service.options.image}}
  # docker_image:
  #   name: "{{marathon_ee_image}}"
  #   repository: "{{hostvars[groups['dcos_slaves_public'][0]]['ansible_' + dcos_nic_name]['ipv4']['address']}}:15000/{{service.options.image}}"
  #   use_tls: no
  #   push: yes
  #   state: present
    