---
- name: Check if dcoc/dist dir exists
  file:
    path: "{{ dcos_bootstrap_root_path }}/genconf/serve"
    state: directory


- name: Generate/Distribute self-signed certificate 
  block:
    - name: Generate self-signed certificate for registry
      command: >
          openssl req -newkey rsa:4096 -nodes -sha256 
            -subj '/emailAddress=jong-gun.kim@hpe.com/C=KR/ST=Seoul/L=Seoul/O=Global Security/OU=IT Deparment/CN={{service.name}}.marathon.l4lb.thisdcos.directory'
            -keyout {{service.name}}.key  -x509 -days 365 -out {{service.name}}.crt
      args:
        chdir: "{{ dcos_bootstrap_root_path }}/genconf/serve"

    - name: Run web container to distribute keys
      become: yes
      docker_container: 
        name: boot-nginx
        image: nginx
        state: started
        ports: "{{dcos_bootstrap_port}}:80"
        volumes: "{{ dcos_bootstrap_root_path }}/genconf/serve:/usr/share/nginx/html:ro"
      changed_when: False

    - name: Insert crts, key to docker cert directory and restart docker engine in each agent
      become: yes
      shell: |
          mkdir -p /etc/docker/certs.d/{{service.name}}.marathon.l4lb.thisdcos.directory:{{service.options.internal_port}} 
          curl -o /etc/docker/certs.d/{{service.name}}.marathon.l4lb.thisdcos.directory:{{service.options.internal_port}}/ca.crt http://{{groups['dcos_cli'][0]}}:{{dcos_bootstrap_port}}/{{service.name}}.crt 
          systemctl restart docker.service
      delegate_to: "{{item}}"
      with_items: "{{ groups['dcos_nodes'] }}"
  when: service.options.is_secure_registry == True


- name: Generate docker conf file, daemon.json for docker cli node 
  become: yes
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json   


- name: Restart docker 
  become: yes
  systemd: name=docker state=restarted
  changed_when: False


