---
- name: Docker login 
  become: yes
  docker_login:
    username: "{{docker_hub_id}}"
    password: "{{docker_hub_pwd}}"
    email: "{{docker_hub_mail}}"


- name: Archive docker credential
  become: yes
  command: tar cvzf docker.tar.gz ~/.docker  
  args:
    chdir: "{{ dcos_bootstrap_root_path }}/genconf/serve"


- name: Docker logout
  docker_login:
    state: absent


- name: Run web container for docker credential
  become: yes
  docker_container: 
    name: boot-nginx
    image: nginx
    state: started
    ports: "{{dcos_bootstrap_port}}:80"
    volumes: "{{ dcos_bootstrap_root_path }}/genconf/serve:/usr/share/nginx/html:ro"
  changed_when: False


- name: Docker pull Marathon-ee image 
  become: yes
  docker_image: 
    name: "{{marathon_ee_image}}" 
    pull: True


- name: Tag and push Marathon-ee to cluster registery
  become: yes
  docker_image:
    name: "{{marathon_ee_image}}"
    repository: "{{hostvars[groups['dcos_slaves_public'][0]]['ansible_' + dcos_nic_name]['ipv4']['address']}}:15000/{{service.options.image}}"
    use_tls: no
    push: yes