---
services:
  kube-dev:
    name: kube-dev
    package: kubernetes
    user: nobody
    role: { name: '*'}
    permissions:
      - { perm: "dcos:superuser",  action: full, desc: "Allows Linux user nobody to execute tasks" }
      - { perm: "dcos:mesos:master:task:user:nobody", action: create, desc: "Allows Linux user nobody to execute tasks" }
    options:
      node_count: 1
      kubelet_cpus: 2
      kubelet_mem: 2048
      kubelet_disk: 1000