---
services:
  - name: marathon-lb-dev
    secret_name: kin-secret
    package: marathon-lb
    user: nobody
    role: { name: '*'}
    permissions:
      - { perm: "dcos:service:marathon:marathon:services%252F", action: read, desc: "Allows Linux user nobody to execute tasks" }
      - { perm: "dcos:service:marathon:marathon:admin:events",  action: read, desc: "Allows Linux user nobody to execute tasks" }
      - { perm: "dcos:mesos:master:task:user:nobody", action: create, desc: "Allows Linux user nobody to execute tasks" }
    options: {
      op1: dummy
    }