
services: 
  marathon-ee-dev:
    name: marathon-ee-dev
    package: marathon-ee
    user: nobody
    role: 
      principal: "{{edcos_superuser}}"
      hostname: "{{hostvars[groups['dcos_slaves'][0]]['ansible_' + dcos_nic_name].ipv4.address}}"
      name: dev
      cpus: 1.5
      mem: 1500
      disks: 1000 
      begin_port: 1025
      end_port: 2180
    permissions: 
      - { perm: "dcos:mesos:master:framework:role:dev", action: create, desc: " " } 
      - { perm: "dcos:mesos:master:reservation:role:dev", action: create, desc: " " }
      - { perm: "dcos:mesos:master:volume:role:dev", action: create, desc: " " }
      - { perm: "dcos:mesos:master:reservation:principal:marathon-ee-dev", action: delete, desc: " " } 
      - { perm: "dcos:mesos:master:volume:principal:marathon-ee-dev", action: delete, desc: " " }
      - { perm: "dcos:mesos:master:task:user:nobody", action: create, desc: "Allows Linux user nobody to execute tasks" }
      - { perm: "dcos:mesos:master:task:app_id:%252F", action: create, desc: " " }
    registry: 
     # repo: "{{docker_private_url}}"
      repo: ""
      image: "mesosphere/marathon-dcos-ee:v1.5.0_1.10.0"
      docker_credential: "{{groups['dcos_bootstrap'][0]}}:{{dcos_bootstrap_port}}/auth/docker.tar.gz"
    

  marathon-ee-svc:  
    name: marathon-ee-svc
    package: marathon-ee
    user: nobody
    role: 
      principal: "{{edcos_superuser}}"
      hostname: "{{hostvars[groups['dcos_slaves'][0]]['ansible_' + dcos_nic_name].ipv4.address}}"
      name: svc
      cpus: 1.5
      mem: 1000
      disks: 1000
      begin_port: 1025
      end_port: 2180
    permissions: 
      - { perm: "dcos:mesos:master:reservation:principal:marathon-ee-svc", action: delete, desc: " " } 
      - { perm: "dcos:mesos:master:volume:principal:marathon-ee-svc", action: delete, desc: " " }
      - { perm: "dcos:mesos:master:task:user:nobody", action: create, desc: "Allows Linux user nobody to execute tasks" }
      - { perm: "dcos:mesos:master:task:app_id:%252F", action: create, desc: " " }
      - { perm: "dcos:mesos:master:framework:role:svc", action: create, desc: " " } 
      - { perm: "dcos:mesos:master:reservation:role:svc", action: create, desc: " " }
      - { perm: "dcos:mesos:master:volume:role:svc", action: create, desc: " " }
    registry: 
      repo: ""
      image: "mesosphere/marathon-dcos-ee:v1.5.0_1.10.0"
      docker_credential: "{{groups['dcos_bootstrap'][0]}}:{{dcos_bootstrap_port}}/auth/docker.tar.gz"
    
