---
services:
  cadvisor: 
    name: cluster-cadvisor
    package: cadvisor
    options: 
      influxdb_name: cluster-influxdb
    
  influxdb:
    name: cluster-influxdb
    package: influxdb
    options: 
      host_db_volume_path: /tmp
   
  grafana:
    name: cluster-grafana
    package: grafana
    options:
      password: admin # no ID setup. defaults is 'admin'
    
   