---
- name: Aquire Auth token 
  shell: dcos config show core.dcos_acs_token
  register: auth_token
  changed_when: False


- name: Get states of dcos nodes 
  command: dcos node --json 
  register: nodes_json
  changed_when: False


- name: Convert node states to variable
  set_fact: 
    nodes: "{{nodes_json.stdout | from_json }}"


- name: Create Dynamic reserve requests
  mesos_dynamic_reserve:
    url: "{{dcos_cluster_url}}"
    token: "{{auth_token.stdout}}"
    mesos_role: "{{role_def}}"
    nodes_status: "{{nodes}}"
  register: body_json


- template:
    src: reserve-request.json.j2
    dest: "/dcos/quota/reserve.json"


- name: Do operation
  uri:
    url: "{{dcos_cluster_url}}/mesos/api/v1"
    method: POST
    validate_certs: False
    headers: 
      Authorization: "token={{auth_token.stdout}}"
      Accept: "application/json" 
    body_format: json
    body: "{{ item }}"
    status_code: 202
  with_items: "{{body_json.state}}"
  when: role_def.name != '*'
