---
- name: Aquire Auth token 
  shell: dcos config show core.dcos_acs_token
  register: auth_token


- name: Get states of dcos nodes 
  command: dcos node --json 
  register: nodes_json


- name: Convert node states to variable
  set_fact: 
    nodes: "{{nodes_json.stdout | from_json }}"


- name: Do operation
  uri:
    url: "https://{{dcos_first_master_internal_ip}}/mesos/api/v1"
    method: POST
    validate_certs: False
    headers: 
      Authorization: "token={{auth_token.stdout}}"
      Accept: "application/json" 
    body_format: json
    body: "{{ lookup('template', 'reserve-request.json.j2') }}"
    status_code: 202
    with_subelements:
      - "{{services}}"
      - role
