---
- name: Create Key pair 
  command: "dcos security org service-accounts keypair {{service_name}}.pem {{service_name}}-pub.pem"


- name: Create service account as ID
  command: "dcos security org service-accounts create -p {{service_name}}-pub.pem -d {{service_name}}' service account' {{service_name}}-id"


- name: Create service secret as Password
  command: dcos security secrets create-sa-secret {% if edcos_security_mode == 'strict'%} --strict {% endif %} {{service_name}}.pem {{service_name}}-id {{service_name}}/password


- name: Create permissions for {{service_name}}
  uri:
    url: "https://{{dcos_cluster_url}}/acs/api/v1/acls/{{item}}"
    method: POST
    return_content: yes
    validate_certs: False
    headers: 
      Authorization: "token={{hostvars[groups['dcos_bootstrap'][0]]['auth_token']}}"
      Content-Type: "application/json"   
  with_items: "{{permissioins}}"


- name: Assign the permissions to {{service_name}}
  uri:
    url: "https://{{dcos_cluster_url}}/acs/api/v1/acls/{{item}}/users/{{service_name}}/{{action}}"
    method: POST
    return_content: yes
    validate_certs: False
    headers: 
      Authorization: "token={{hostvars[groups['dcos_bootstrap'][0]]['auth_token']}}"
      Content-Type: "application/json"   
  with_items: "{{permissioins}}"