---
- name: Download docker private registry token 
  get_url:
    url: "http://{{groups['dcos_bootstrap'][0]}}:{{dcos_bootstrap_port}}/auth/docker.tar.gz"
    dest: "docker.tar.gz"

- name: Insert docker token to docker_credentials file
  become: yes
  copy:
    content: "{{hostvars[groups['dcos_bootstrap'][0]].docker_token}}"
    dest: /etc/mesosphere/docker_credentials
    backup: yes


- set_fact: 
    svc_name: "{{ (inventory_hostname in groups['dcos_slaves']) | ternary('dcos-mesos-slave', 'dcos-mesos-slave-public') }}"
    tags: distro_token


- name: Restart {{svc_name}} 
  become: yes
  systemd: name={{svc_name}} state=restarted