---
- include: util-dcos-bugfix.yml
  when: edcos_security_mode == "strict"

- name: "Reserve dynamic resources based on roles"
  hosts: dcos_cli[0]
  vars_files:
    - pkg-desc/marathon-ee.yml 
  roles:
    - { role: dcos/node/quota, op_type: reserve_resources, role_def: "{{ services['marathon-ee-dev'].role }}" } 
  environment: "{{ proxy_env }}"
