---
- hosts: dcos_bootstrap
  gather_facts: False
  become: yes
  roles:
    - { role: dcos/bootstrap/upgrade } 
    - { role: dcos/bootstrap/boot_web } 
  environment: "{{ proxy_env }}"


- name: "Upgrade security of Masters"
  gather_facts: False
  hosts: dcos_masters
  become: yes
  roles:
    - { role: dcos/node/upgrade-node, node_type: master} 
  environment: "{{ proxy_env }}"



- name: "Upgrade security of Slaves/Slaves public"
  gather_facts: False
  hosts: dcos_slaves:dcos_slaves_public
  become: yes
  roles:
    - { role: dcos/node/upgrade-node, node_type: slave} 
  environment: "{{ proxy_env }}"

