---

# not workgin :     http[s]://<cluster-url>/dcos-metadata/bootstrap-config.json.
- name: "Discovery security mode of the cluster"
  hosts: dcos_bootstrap
  gather_facts: False
  roles:
    - dcos/bootstrap/upgrade
    - dcos/node/bootstrap 
  environment: "{{ proxy_env }}"


- name: "Run Bootstrap web server"
  gather_facts: False
  hosts: "dcos_bootstrap"
  become: yes
  roles:
    - { role: dcos/node/bootstrap } 
  environment: "{{ proxy_env }}"


- name: "Upgrade security of Masters "
  gather_facts: False
  hosts: "dcos_masters"
  become: yes
  roles:
    - { role: dcos/node/upgrade-node, node_type: master} 
  environment: "{{ proxy_env }}"



- name: "Upgrade security of Slaves/public "
  gather_facts: False
  hosts: dcos_slaves:dcos_slaves_public
  become: yes
  roles:
    - { role: dcos/node/upgrade-node, node_type: slave} 
  environment: "{{ proxy_env }}"

