---
- name: Generate DC/OS upgrade scripts for security
  hosts: dcos_bootstrap
  gather_facts: False
  tags: ['upgrade-security']
  roles:
    - dcos/bootstrap/upgrade 
    - { role: dcos/bootstrap/boot_web, tags: [ 'upgrade-master' ] }
  environment: "{{ proxy_env }}"


- name: "Upgrade security of Masters"
  gather_facts: False
  hosts: dcos_masters
  tags: ['upgrade-security']
  serial: 1
  roles:
    - { role: dcos/node/upgrade-node, node_type: master} 
  environment: "{{ proxy_env }}"


- name: "Upgrade security of Slaves"
  gather_facts: False
  hosts: dcos_slaves
  tags: ['upgrade-security-slave']
  serial: 1
  roles:
    - { role: dcos/node/upgrade-node, node_type: slave } 
  environment: "{{ proxy_env }}"


- name: "Upgrade security of Slaves public"
  gather_facts: False
  hosts: dcos_slaves_public
  tags: ['upgrade-security']
  serial: 1
  roles:
    - { role: dcos/node/upgrade-node, node_type: slave-public } 
  environment: "{{ proxy_env }}"
