---
- name: Generate DC/OS upgrade scripts for security
  hosts: dcos_bootstrap
  gather_facts: False
  roles:
    - dcos/bootstrap/upgrade 
    - dcos/bootstrap/boot_web 
  environment: "{{ proxy_env }}"


- name: "Upgrade security of Masters"
  gather_facts: False
  hosts: dcos_masters
  serial: 1
  roles:
    - { role: dcos/node/upgrade-node, node_type: master} 
  environment: "{{ proxy_env }}"


- name: "Upgrade security of Slaves/Slaves public"
  gather_facts: False
  hosts: dcos_slaves:dcos_slaves_public
  serial: 1
  roles:
    - { role: dcos/node/upgrade-node, node_type: slave} 
  environment: "{{ proxy_env }}"

