--- 

- name: "Install CLI and Enterprise CLI"
  hosts: dcos_cli
  tags: ['pkg']
  gather_facts: False
  roles:
    - dcos/packages/cli
  environment: "{{ proxy_env }}"


- name: "Create local facts of DC/OS in boostrap node "
  gather_facts: False
  hosts: dcos_bootstrap
  tags: ['install', 'dcos-fact']
  environment: "{{ proxy_env }}"
  roles: 
    - { role: dcos/bootstrap/local-facts, op_type: create }
