---

- name: Install Marathon-ee
  hosts: dcos_cli[0]
  vars_files: 
    - pkg-desc/kubernetes.yml   
  roles:
    - { role: dcos/packages/service-account, service:  "{{services['kube-dev']}}" , when: dcos_is_enterprise == True } 
    - { role: dcos/packages/installer, service: "{{services['kube-dev']}}", tags: kube }
  environment: "{{ proxy_env }}"


