--- 

- include: pkg-install-marathon-lb.yml

- name: Install cadvisor
  gather_facts: False
  hosts: dcos_cli[0]
  vars_files: 
    - pkg-desc/monitoring.yml
  tags: ['pkg']
  roles:
    - { role: dcos/packages/installer, service: "{{services['cadvisor']}}" }
    - { role: dcos/packages/installer, service: "{{services['influxdb']}}" }
    - { role: dcos/packages/installer, service: "{{services['grafana']}}" }
  environment: "{{ proxy_env }}"