--- 
- name: "Install docker private registry with auth"
  gather_facts: False
  hosts: dcos_cli[0]
  vars_files: 
    - pkg-desc/registry-cesanta.yml
  roles:
    - { role: dcos/packages/installer, custom_type: none, pre_tasks: cesanta, post_tasks: cesanta }
  environment: "{{ proxy_env }}"


- name: "Distribute private registry auth token"
  gather_facts: False
  hosts: dcos_slaves:dcos_slaves_public
  tasks:
    - name: Download docker private registry token 
      get_url:
        url: "http://{{groups['dcos_bootstrap'][0]}}:{{dcos_bootstrap_port}}/auth/docker.tar.gz"
        dest: "docker.tar.gz"

    - name: Insert docker token to docker_credentials file
      become: yes
      copy:
        content: "{{hostvars[groups['dcos_bootstrap'][0]].docker_token}}"
        dest: /etc/mesosphere/docker_credentials
        backup: yes
    

    - set_fact: 
        svc_name: "{{ (inventory_hostname in groups['dcos_slaves']) | ternary('dcos-mesos-slave', 'dcos-mesos-slave-public') }}"
      
    - name: Restart {{svc_name}} 
      become: yes
      systemd: name={{svc_name}} state=restarted
      
  environment: "{{ proxy_env }}"
