---
- include: util-dcos-bugfix.yml
  when: edcos_security_mode == "strict"

- name: Install custom marathon
  hosts: dcos_cli[0]
  vars_files: 
    - pkg-desc/marathon-ee.yml   
  roles:
    - { role: dcos/node/quota, op_type: reserve_resources } 
    - { role: dcos/packages/service-account } 
    - { role: dcos/packages/installer, pre_tasks: marathon-ee, tags: marathon-ee}
  environment: "{{ proxy_env }}"

