---

- name: Install custom marathon
  hosts: dcos_cli[0]
  vars_files: 
    - pkg-desc/marathon.yml
  roles:
    - { role: dcos/node/quota, when: edcos_security_mode != 'disabled' } 
    - { role: dcos/node/service-account, when: edcos_security_mode == 'strict' } 
    - { role: dcos/packages/installer }
  environment: "{{ proxy_env }}"

