---
- assert:
    that: dcos_is_enterprise == True
    msg: Only Enterprise version supports Marathon-ee 


- include: util-dcos-bugfix.yml
  when: edcos_security_mode == "strict"


- name: Install Marathon-ee
  hosts: dcos_cli[0]
  vars_files: 
    - pkg-desc/marathon-ee.yml   
  roles:
    - { role: dcos/node/quota, role_def: "{{services['marathon-ee-dev'].role}}" } 
    - { role: dcos/packages/service-account, service:  "{{services['marathon-ee-dev']}}" } 
    - { role: dcos/packages/installer, custom_type: app, service: "{{services['marathon-ee-dev']}}"}
  environment: "{{ proxy_env }}"


- name: Install Marathon-ee
  hosts: dcos_cli[0]
  vars_files: 
    - pkg-desc/marathon-ee.yml   
  roles:
    - { role: dcos/node/quota,  role_def: "{{services['marathon-ee-svc'].role}}" } 
    - { role: dcos/packages/service-account, service:  "{{services['marathon-ee-svc']}}" } 
    - { role: dcos/packages/installer, custom_type: app, service: "{{services['marathon-ee-svc']}}"}
  environment: "{{ proxy_env }}"

