---
- include: util-dcos-bugfix.yml
  when: edcos_security_mode == "strict"
  
- name: Install Distributed Tensorflow
  hosts: dcos_cli[0]
  vars_files: 
    - pkg-desc/tensorflow.yml   
  roles:
    # - { role: dcos/node/quota } 
    - { role: dcos/packages/service-account, when: dcos_is_enterprise == True } 
    - { role: dcos/packages/installer }
  environment: "{{ proxy_env }}"

