
--- 

- include: util-update-fact-cache.yml

- name: Install & Configure prerequisites for DC/OS
  hosts: dcos_nodes:dcos_bootstrap
  gather_facts: False
  become: yes
  roles:
    - role: common/preconditions
  environment: "{{ proxy_env }}"
  