
--- 

- include: util-update-fact-cache.yml

- name: Install & Configure prerequisites for DC/OS
  tags: ['step-1'] 
  hosts: dcos_nodes
  gather_facts: False
  become: yes
  roles:
    - common/preconditions 
  environment: "{{ proxy_env }}"
  