
---

- name: "Install docker engine"
  gather_facts: False
  hosts: dcos_nodes
  tags: ['pre-steps', 'install'] 
  become: yes
  roles:
    - { role: common/docker, tags: ['pre-steps'] }
  environment: "{{ proxy_env }}"
