---
- name: "Deploy DC/OS masters"
  gather_facts: False
  hosts: dcos_masters
  tags: ['step-3']
  roles:
    - { role: dcos/bootstrap/deploy-node, node_type: master, service_name: dcos-mesos-master } 
  environment: "{{ proxy_env }}"


- name: "Deploy DC/OS slaves"
  gather_facts: False
  hosts: dcos_slaves
  tags: ['step-3']
  roles:
    - { role: dcos/bootstrap/deploy-node, node_type: slave, service_name: dcos-mesos-slave }
  environment: "{{ proxy_env }}"


- name: "Deploy DC/OS slaves public"
  gather_facts: False
  hosts: dcos_slaves_public
  tags: ['step-3']
  roles:
    - { role: dcos/bootstrap/deploy-node, node_type: slave_public, service_name: dcos-mesos-slave-public } 
  environment: "{{ proxy_env }}"