--- 
- name: "Remove DC/OS 1.9 bug for mesos API "
  become: yes
  hosts: dcos_masters
  tasks:
  - name: Remove mesos HTTP endpoint, /api/v1 from master firewalll 
    lineinfile:
      dest: /opt/mesosphere/etc/mesos/master_firewall.json
      regexp: "^'/api/v1,'"
      state: absent


  - name: Restat dcos-mesos-master
    systemd: name=dcos-mesos-master state=restarted  
    schanged_when: false

