---

- hosts: dcos_bootstrap
  gather_facts: False
  tasks:
  - name: Generate ssh key for ansible 
    command: ssh-keygen -b 2048 -t rsa -f ~/.ssh/dcos -q -N ""
    args: 
      creates: yes

- hosts: all
  gather_facts: False
  tasks:
  - name: Install ssh pub key to authorized_key
    authorized_key:
     user: "{{ansible_user_id}}" 
     key: "{{ lookup('file', '~/.ssh/dcos.pub')}}" 
     state: present
