--- 
- name: "Remove DC/OS 1.9 bug for mesos API "
  become: yes
  hosts: dcos_masters
  tasks:
  - name: Remove mesos HTTP endpoint, /api/v1 from master firewalll 
    lineinfile:
      dest: /opt/mesosphere/etc/mesos/master_firewall.json
      regexp: '"\/api\/v1",'
      state: absent

  - name: Restat dcos-mesos-master
    systemd: name=dcos-mesos-master state=restarted  
    changed_when: false
    
  - name: Wait for mesos master running
    become: yes
    shell: "systemctl status dcos-mesos-master"
    register: result
    until: result.stdout.find("running") != -1
    retries: 1000
    delay: 30 # unit, second
    tags: upgrade-master
    changed_when: no