--- 

- debug:
    msg: "proxy - {{proxy_env}}"


- name: Create DC/OS user directory structure
  become: yes
  file: 
    path: "{{ dcos_bootstrap_root_path }}/{{item}}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  with_items:
    - packages
    - quota
    - examples
  

- name: Copy marathon examples to {{ dcos_bootstrap_root_path }}/examples
  copy:
    src: examples/
    dest: "{{ dcos_bootstrap_root_path }}/examples"
    

- name: Download DC/OS client
  become: yes
  get_url:
    url: "https://downloads.dcos.io/binaries/cli/linux/x86-64/dcos-{{dcos_cli_version}}/dcos"
    dest: /usr/local/bin/dcos
    validate_certs: no
    mode: 0755
    force: no
  environment: "{{proxy_env}}" 


- name: Download root Certificate from master
  get_url: 
    url: "{{ dcos_cluster_url }}/ca/dcos-ca.crt"
    dest: "{{ dcos_bootstrap_root_path }}/dcos-ca.crt"
    validate_certs: no
    mode: 0755
  when: dcos_is_enterprise

# in dcos cli 1.10 option for cert, --ca-certs={{ dcos_bootstrap_root_path }}/dcos-ca.crt is not working 
- name: Set dcos master url to dcos cli 
  command: "dcos cluster setup {{ dcos_cluster_url }} --insecure --username={{edcos_superuser}} --password={{edcos_superuser_pwd}}" 
  #command: "{{ (dcos_cli_version | version_compare('1.10', operator='ge', strict=True)) | ternary('dcos cluster setup ', 'dcos config set core.dcos_url ')}} {{ dcos_cluster_url }}"


# - name: Confige dcos with root certificate
#   command: "dcos config set core.ssl_verify {{ dcos_bootstrap_root_path }}/dcos-ca.crt"
#   when: dcos_is_enterprise


# - name: Login to DC/OS
#   command: dcos auth login --username={{edcos_superuser}} --password={{edcos_superuser_pwd}}
#   when: dcos_is_enterprise
  

- name: Install Enterprise CLI
  command: dcos package install --cli dcos-enterprise-cli --yes
  when: dcos_is_enterprise
  environment: "{{proxy_env}}"
  
  