
---  
- name: Generate docker registry config 
  template:
    src: registry-opt.json.j2
    dest: "{{ dcos_bootstrap_root_path }}/packages/registry-opt.json"


- name: Install Docker registry 
  command: "dcos package install --options={{ dcos_bootstrap_root_path }}/packages/registry-opt.json registry --yes"