---

- name: debug home dir 
  debug: 
    msg: "{{ ansible_user_dir }}"

- block: 
    - name: Download docker registry token 
      get_url:
        url: "{{dcos_bootstrap_url}}/auth/docker.tar.gz"
        dest: "{{ ansible_user_dir }}/docker.tar.gz"
        force: yes
    - name: Unarchive  docker.tar.gz
      unarchive:
        src: "{{ ansible_user_dir }}/docker.tar.gz"
        dest: /tmp
        remote_src: yes
    - name: Insert docker token to /etc/mesosphere/docker_credentials file
      become: yes
      copy:
        #content: "{{hostvars[groups['dcos_bootstrap'][0]].docker_token | to_nice_json}}" # copy module 'contents is not beautiful 
        remote_src: yes
        src: /tmp/.docker/config.json
        dest: /etc/mesosphere/docker_credentials
        backup: yes
    - name: Restart dcos agent 
      become: yes
      systemd: name={{ (item in groups['dcos_slaves']) | ternary('dcos-mesos-slave', 'dcos-mesos-slave-public') }} state=restarted
  delegate_to: "{{item}}"
  with_inventory_hostnames:
    - dcos_slaves:dcos_slaves_public