--- 
- name: Copy /usr/bin/docker 
  become: yes
  shell: |
       cp -p /usr/bin/docker /usr/bin/docker-orig
       cp -p /usr/bin/docker /tmp/docker-wrapper
  when: node_type != "master"


- name: Update /usr/bin/docker  
  become: yes
  shell:
    cmd: |
        tee /tmp/docker-wrapper >/dev/null <<"EOF"
         #!/usr/bin/env sh
         unset LD_LIBRARY_PATH
         /usr/bin/docker-orig "$@"
        EOF
  when: node_type != "master"


- name: Move /usr/bin/docker  
  become: yes
  shell: sudo mv -f /tmp/docker-wrapper /usr/bin/docker
  when: node_type != "master"


- name: Download the DC/OS installer from the NGINX Docker container
  get_url:
    url: "{{hostvars[groups['dcos_bootstrap'][0]]['upgrade_url']}}"
    dest: /tmp/dcos/dcos_node_upgrade.sh
    force: no #if yes, if it keeps downloading


- name: Install dcos "{{ node_type }}"
  become: yes
  command: "bash dcos_node_upgrade.sh"
  args:
    chdir: /tmp/dcos


- name: Wait for dcos-mesos-{{node_type}} running
  become: yes
  shell: "systemctl status dcos-mesos-{{node_type}}"
  register: result
  until: result.stdout.find("running") != -1
  retries: 5
  delay: 10
  

- name: Move /usr/bin/docker  
  become: yes
  shell: sudo mv -f /usr/bin/docker-orig /usr/bin/docker
  when: node_type != "master"
