
- name: Update /usr/bin/docker  
  become: yes
  shell: |
       sudo cp -p /usr/bin/docker /usr/bin/docker-orig
       sudo cp -p /usr/bin/docker /tmp/docker-wrapper
       sudo tee /tmp/docker-wrapper >/dev/null <<"EOF"
         #!/usr/bin/env sh
         unset LD_LIBRARY_PATH
         /usr/bin/docker-orig "$@"
        EOF
        sudo mv -f /tmp/docker-wrapper /usr/bin/docker
  when: node_type != "master"


- name: Download the DC/OS installer from the NGINX Docker container
  get_url:
    url: "{{upgrade_url}}"
    dest: /tmp/dcos/dcos_node_upgrade.sh
    force: no #if yes, if it keeps downloading


- name: Install dcos "{{ node_type }}"
  become: yes
  command: "bash dcos_node_upgrade.sh"
  args:
    chdir: /tmp/dcos

