--- 

- name: Download the DC/OS installer from the NGINX Docker container
  get_url:
    url: "{{hostvars[groups['dcos_bootstrap'][0]]['upgrade_url']}}"
    dest: /tmp/dcos/dcos_node_upgrade.sh
    force: no #if yes, if it keeps downloading
  tags: upgrade-mesos-wait


- name: Upgrade master node 
  become: yes
  command: "bash dcos_node_upgrade.sh"
  args:
    chdir: /tmp/dcos
  tags: upgrade-mesos-wait


- name: Wait for mesos master running
  become: yes
  shell: "systemctl status dcos-mesos-master"
  register: result
  until: result.stdout.find("running") != -1
  retries: 1000
  delay: 50 # unit, second
  tags: upgrade-mesos-wait


# registrar/log/recovered with a value of 1
- name: Verify mertrict snapshot of mesos master
  uri:
    url: "https://{{dcos_first_master_internal_ip}}:5050/metrics/snapshot"
    method: GET
    return_content: yes
    validate_certs: False
    headers: 
      Accept: "application/json"
  register: is_recovered
  until: (is_recovered.result.content | from_json)['recovered'] != 1.0
  retries: 1000
  delay: 100
  tags: upgrade-mesos-wait

- debug: msg="{{is_recovered}}"
  