--- 

- name: Download the DC/OS installer from the NGINX Docker container
  get_url:
    url: "{{hostvars[groups['dcos_bootstrap'][0]]['upgrade_url']}}"
    dest: /tmp/dcos/dcos_node_upgrade.sh
    force: no #if yes, if it keeps downloading


- name: Upgrade master node 
  become: yes
  command: "bash dcos_node_upgrade.sh"
  args:
    chdir: /tmp/dcos


- name: Wait for mesos master running
  become: yes
  shell: "systemctl status dcos-mesos-{{node_type}}"
  register: result
  until: result.stdout.find("running") != -1
  retries: 1000
  delay: 100 # unit, second


# registrar/log/recovered with a value of 1
- name: Aquire DC/OS metadata
  uri:
    url: "https://{{dcos_first_master_internal_ip}}:5050/metrics/snapshot"
    method: GET
    return_content: yes
    validate_certs: False
    headers: 
      Authorization: "token={{auth_token.stdout}}"
      Accept: "application/json"
  register: is_recovered
