--- 

- name: Download the DC/OS installer from the NGINX Docker container
  get_url:
    url: "{{hostvars[groups['dcos_bootstrap'][0]]['upgrade_url']}}"
    dest: /tmp/dcos/dcos_node_upgrade.sh
    force: no #if yes, if it keeps downloading


- name: Upgrade master node 
  become: yes
  command: "bash dcos_node_upgrade.sh"
  args:
    chdir: /tmp/dcos


- name: Wait for mesos master running
  become: yes
  shell: "systemctl status dcos-mesos-master"
  register: result
  until: result.stdout.find("running") != -1
  retries: 1000
  delay: 30 # unit, second
  tags: upgrade-master
  changed_when: no


- name: Verify mertrict snapshot of mesos master
  uri:
    url: "https://{{inventory_hostname}}:5050/metrics/snapshot"
    method: GET
    return_content: yes
    validate_certs: False
    headers: 
      Authorization: "token={{hostvars[groups['dcos_bootstrap'][0]]['auth_token']}}"
      Accept: "application/json"   
  register: is_recovered
  until: (is_recovered.content | from_json)['registrar/log/recovered'] == 1.0
  retries: 1000
  delay: 30
  tags: upgrade-master
  changed_when: no


- debug: msg="{{is_recovered.content}}"
  