--- 
- name: Copy /usr/bin/docker 
  become: yes
  shell: |
       cp -p /usr/bin/docker /usr/bin/docker-orig
       cp -p /usr/bin/docker /tmp/docker-wrapper


- name: Update /usr/bin/docker  
  become: yes
  shell:
    cmd: |
        tee /tmp/docker-wrapper >/dev/null <<"EOF"
         #!/usr/bin/env sh
         unset LD_LIBRARY_PATH
         /usr/bin/docker-orig "$@"
        EOF


- name: Move /usr/bin/docker  
  become: yes
  shell: sudo mv -f /tmp/docker-wrapper /usr/bin/docker


- name: Download the DC/OS installer from the NGINX Docker container
  get_url:
    url: "{{hostvars[groups['dcos_bootstrap'][0]]['upgrade_url']}}"
    dest: /tmp/dcos/dcos_node_upgrade.sh
    force: no #if yes, if it keeps downloading


- name: Upgrade "{{node_typ}}"
  become: yes
  command: "bash dcos_node_upgrade.sh"
  args:
    chdir: /tmp/dcos


- name: Wait for mesos {{svc_name}} running
  become: yes
  shell: "systemctl status {{svc_name}}"
  register: result
  until: result.stdout.find("running") != -1
  retries: 1000
  delay: 30 # unit, second
  tags: upgrade-slave
  changed_when: no


- name: Verify mertrict snapshot of mesos slave
  uri:
    url: "https://{{inventory_hostname}}:5051/metrics/snapshot"
    method: GET
    return_content: yes
    validate_certs: False
    headers: 
      Authorization: "token={{hostvars[groups['dcos_bootstrap'][0]]['auth_token']}}"
      Accept: "application/json"   
  register: is_registered
  until: (is_registered.content | from_json)['slave/registered'] == 1.0
  retries: 1000
  delay: 30
  changed_when: no


- debug: msg="{{ 'registered:' (is_registered.content | from_json)['slave/registered'] }}"


- name: Move /usr/bin/docker  
  become: yes
  shell: mv -f /usr/bin/docker-orig /usr/bin/docker