---


# something wrong with include_vars, if i use expresseion above directly here so. use variable using set_fact
- include_vars: CentOS.yml

- set_fact:
    docker_pkg_name: "{{ 'docker-ce' if docker_type == 'community' else 'docker-ee'}}"

- name: Add the YUM Docker repository in CentOS
  get_url:
    url: "{{ docker_repo }}"
    dest: "/etc/yum.repos.d"
    force: no
    validate_certs: no
  environment: "{{proxy_env}}"


# - name: Add the YUM Docker repository in CentOS
#   yum_repository:
#     name: dockerrepo
#     description: Docker Repository.
#     baseurl: "{{ docker_repo }}"
#     enabled: yes
#     gpgcheck: yes
#     gpgkey:  http://yum.dockerproject.org/gpg
