---


# something wrong with include_vars, if i use expresseion above directly here so. use variable using set_fact
- include_vars: CentOS.yml

- name: Add the YUM Docker repository in CentOS
  yum_repository:
    name: dockerrepo
    description: Docker Repository.
    baseurl: "{{ docker_repo }}"
    enabled: yes
    gpgcheck: yes
    gpgkey:  http://yum.dockerproject.org/gpg
