---

# Variables setup



- include_vars: "{{ ansible_distribution }}.yml"

- debug:
    msg: "is csengine? {{ is_csengine }}, version: {{ docker_version }}, repo:  {{ docker_repo }}"

- include: "install_engine.yml"
  
