---

# Variables setup

- debug:
    msg: "docker package? {{ docker_type }}, linux distro: {{ansible_distribution}}, docker ver: {{docker_version}}"

# something wrong with include_vars, if i use expresseion above directly here so. use variable using set_fact
- include: "{{docker_type}}.yml"
  
- include: "install_engine.yml"